import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Font definition remains here to be available globally
const iranYekan = localFont({
  src: [
    { path: "./fonts/IranYekanX/IRANYekanX-Thin.ttf", weight: "100" },
    { path: "./fonts/IranYekanX/IRANYekanX-UltraLight.ttf", weight: "200" },
    { path: "./fonts/IranYekanX/IRANYekanX-Light.ttf", weight: "300" },
    { path: "./fonts/IranYekanX/IRANYekanX-Regular.ttf", weight: "400" },
    { path: "./fonts/IranYekanX/IRANYekanX-Medium.ttf", weight: "500" },
    { path: "./fonts/IranYekanX/IRANYekanX-DemiBold.ttf", weight: "600" },
    { path: "./fonts/IranYekanX/IRANYekanX-Bold.ttf", weight: "700" },
    { path: "./fonts/IranYekanX/IRANYekanX-ExtraBold.ttf", weight: "800" },
    { path: "./fonts/IranYekanX/IRANYekanX-Black.ttf", weight: "900" },
    { path: "./fonts/IranYekanX/IRANYekanX-ExtraBlack.ttf", weight: "950" },
  ],
  variable: "--font-yekan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranYekan.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
