import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure the IRANSansX local font
const iranSans = localFont({
  src: [
    {
      path: './fonts/IranSansX/IRANSansX-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-UltraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-DemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-Black.ttf',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/IranSansX/IRANSansX-ExtraBlack.ttf',
      weight: '950',
      style: 'normal',
    },
  ],
  variable: "--font-iran",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${iranSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}