name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Trigger only on semantic version tags, e.g., v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker image with Git tag
      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}   # Extract tag name from ref
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/portfolio-website:$TAG
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
